### ISSUE TITLE
Problemer med Make downlaod

### ISSUE THREAD

**Issue by ghost** [fui/fui-kk#105]
Jeg får følgende feilmelding når jeg kjører make download:

Traceback (most recent call last):
  File "fui_kk/download_reports.py", line 238, in <module>
    main()
  File "fui_kk/download_reports.py", line 227, in main
    login(driver, args)
  File "fui_kk/download_reports.py", line 62, in login
    userfield = driver.find_element_by_css_selector('#username')
  File "/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: {"errorMessage":"Unable to find element with css selector '#username'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Content-Length":"100","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:50155","User-Agent":"selenium/3.141.0 (python mac)"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"css selector\", \"value\": \"#username\", \"sessionId\": \"00e76f40-a35f-11eb-bdbb-91c016a5ef96\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/00e76f40-a35f-11eb-bdbb-91c016a5ef96/element"}}
Screenshot: available via screen

make: *** [download] Error 1

Vi er ganske sikre på at feilen kommer av at nettskjema har oppdatert innloggingen sin. Jeg har prøvd å sende inn mitt eget brukernavn og passord fremfor fui sitt, men det har ikke hjulpet.

**Comment by olehermanse** [comment]
@eirberg1 ser ut som denne nye innlogginsløsningen er ganske mye mer komplisert enn det var før. Kan hende dette blir vanskelig å fikse. Har UIet etter man logger seg inn endret seg mye også?

Jeg ville prøvd å kontakte USIT (igjen), som vi har prøvd tidligere, og si at dere trenger å laste ned alle filene i nettskjema knyttet til FUI kontoen. Hvis de kan gi dere dette, eller en knapp for Last ned alt, hadde det hjulpet mye. I utgangspunktet bør dette være enkelt for dem å tilby, og siden dere ikke har en løsning som fungerer lenger, kanskje de skjønner alvoret og prioriterer det.

Hvis dere får en download all knapp (som laster ned en .zip elns) så trenger dere ikke dette scriptet lenger.

**Comment by ghost** [comment]
Takk for hjelp! Vi skal prøve å purre på USIT:)
