### ISSUE TITLE
Error in responses.py

### ISSUE THREAD

**Issue by Berstad** [fui/fui-kk#43]
When attempting to use make all on windows, the following error is encountered in reponses.py

```
PS C:\Users\\fui-kk> make all
python scripts/responses.py -s all
Traceback (most recent call last):
  File "scripts/responses.py", line 106, in <module>
    main()
  File "scripts/responses.py", line 103, in main
    parse_tsv_files(args.input, args.output)
  File "scripts/responses.py", line 97, in parse_tsv_files
    content = parse_course_tsv(tsv_filename)
  File "scripts/responses.py", line 59, in parse_course_tsv
    responses[labels[i]].append(responses_raw[r][i])
IndexError: list index out of range
python scripts/scales.py all
python scripts/course.py data
python scripts/semester.py
Traceback (most recent call last):
  File "scripts/semester.py", line 50, in <module>
    main("./data/"+sem)
  File "scripts/semester.py", line 35, in main
    for f in os.listdir(semester_dir+"/outputs/stats"):
FileNotFoundError: [WinError 3] The system cannot find the path specified: './data/H2016/outputs/stats'
make.exe":  [json] Error 1
PS C:\Users\\fui-kk>
```

**Comment by olehermanse** [comment]
Should be fixed by #45
