### ISSUE TITLE
Encoding error on windows (download)

### ISSUE THREAD

**Issue by olehermanse** [fui/fui-kk#44]
```
PS C:\Users\olehermanse\code\fui-kk> python3 .\scripts\download_reports.py -u fui -f "H2016"
Password:
Filter matched 59 of 767 forms
Fetching Kursevaluering INF1000 - H2016 (id=77980)
Traceback (most recent call last):
  File ".\scripts\download_reports.py", line 208, in <module>
    main()
  File ".\scripts\download_reports.py", line 202, in main
    download_files(driver, args)
  File ".\scripts\download_reports.py", line 180, in download_files
    write_to_file(tsv_path, name_underscored, 'tsv', response.text)
  File ".\scripts\download_reports.py", line 79, in write_to_file
    f.write(content)
  File "C:\Program Files\Python35\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 27697-27698: character maps to <undefined>
```

**Comment by olehermanse** [comment]
Should be fixed by #45
