### ISSUE TITLE
Indexerror

### ISSUE THREAD

**Issue by dennisno** [fui/fui-kk#94]
Hei.
Prøver å kjøpe make responses etter at jeg har kjørt make download, men ender kun med at jeg får veldig mange slike errormeldinger.

```
Traceback (most recent call last):
  File "fui_kk/responses.py", line 106, in <module>
    main()
  File "fui_kk/responses.py", line 103, in main
    parse_tsv_files(args.input, args.output)
  File "fui_kk/responses.py", line 97, in parse_tsv_files
    content = parse_course_tsv(tsv_filename)
  File "fui_kk/responses.py", line 59, in parse_course_tsv
    responses[labels[i]].append(responses_raw[r][i])
IndexError: list index out of range
```

**Comment by olehermanse** [comment]
Hei!

Så nå at @martava hadde noen endringer her: https://github.com/fui/fui-kk/pull/93

Brukte du de, eller master?

Jeg trykket akkurat merge, så du burde få de ved å kjøre `git pull`.

**Comment by dennisno** [comment]
Hei
Jeg bruker nok master, skal kjøre git pull når jeg får mulighet
 Takk
Mvh
Dennis Norheim

**Comment by dennisno** [comment]
Har akkurat prøvd med endringene til  @martava og får fortsatt samme feil da jeg kjører "make responses". 
![image](https://user-images.githubusercontent.com/36472735/45411205-e5efea80-b673-11e8-81cd-9ee15d27c94b.png)

**Comment by olehermanse** [comment]
@dennisno Ok, takk. Kjører du i cmd, powershell, eller bash (WSL)?

**Comment by dennisno** [comment]
Kjører i bash(WSL) da min laptop ikke vil kjøre "make" i cmd eller powershell.
